name: branch
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
env:
  DEVELOPER_DIR: /Applications/Xcode_13.4.1.app/Contents/Developer
jobs:
  build:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: Pods
          key: '${{ runner.os }}-pods-${{ hashFiles(''**/Podfile.lock'') }}'
          restore-keys: |
            ${{ runner.os }}-pods-
      - name: Swiftlint
        uses: maierj/fastlane-action@v1.4.0
        with:
          lane: run_swiftlint
          skip-tracking: false
      - name: UnitTest
        uses: maierj/fastlane-action@v1.4.0
        with:
          lane: run_all_tests
          skip-tracking: false
      - name: UnitTest
        uses: maierj/fastlane-action@v1.4.0
        with:
          lane: run_all_tests
          skip-tracking: false

